# Generated by Django 3.2.5 on 2022-02-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
            options={
                'verbose_name': 'Marker',
                'verbose_name_plural': 'Markers',
            },
        ),
    ]
