# Generated by Django 3.2.5 on 2022-02-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
