# Generated by Django 3.2.5 on 2022-02-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_marker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
