# Generated by Django 3.2.5 on 2022-02-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_marker_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='caption',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
