# Generated by Django 3.2.5 on 2022-02-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marker_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
