# Generated by Django 3.2.5 on 2022-02-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_marker_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='uid',
            field=models.CharField(default=7890, max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
    ]
