# Generated by Django 3.2.5 on 2022-02-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220219_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='uid',
            field=models.CharField(max_length=7),
        ),
    ]
