# Generated by Django 3.2.5 on 2022-02-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_marker_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='uid',
        ),
    ]
