# Generated by Django 3.2.5 on 2022-02-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_marker_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='uid',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
