# Generated by Django 3.2.5 on 2022-02-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_marker_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marker',
            options={},
        ),
    ]
