# Generated by Django 3.2.5 on 2022-02-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_marker_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
