# Generated by Django 3.2.5 on 2022-02-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_marker_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark', models.BooleanField()),
            ],
        ),
    ]
