# Generated by Django 3.2.5 on 2022-02-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mapmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmode',
            name='name',
            field=models.CharField(default='mdoe', max_length=5),
            preserve_default=False,
        ),
    ]
